repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-case-conflict
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.40.0
    hooks:
    -   id: markdownlint-fix
-   repo: https://github.com/samueljsb/mirrors-node-markdown-spellcheck
    rev: v1.3.1
    hooks:
    -   id: mdspell
        args: ['--report', '--ignore-numbers']
