baseURL = 'https://samueljsb.co.uk/til'
languageCode = 'en-gb'
title = 'TIL'
theme = "rocinante"

[permalinks]
  posts = "/:year/:month/:title/"

[markup]
  [markup.highlight]
    style = "github"

[params]
  author = "Samuel Searles-Bryant"
  about = ""

  mainSections = ["posts"]

  [[params.links]]
    [[params.links.link]]
      name = "RSS"
      href = "index.xml"
